ifpe-20151-dsw3-projeto/src/java/jsf/AcompanhamentoMB.java
package jsf;

/**
 *
 * @author João Henrique 2
 */
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import jpa.entidades.Acompanhamento;
import jpa.controle.AcompanhamentoDao;
import jpa.entidades.TCC;

@ManagedBean(name = "AcompanhamentoMB")
@SessionScoped
public class AcompanhamentoMB implements Serializable{

    private AcompanhamentoDao acompanhamentoDAO;
    private Acompanhamento acompanhamento;
    private List<Acompanhamento> AcompanhamentoList;
    
    public AcompanhamentoMB(){
        
        acompanhamentoDAO = new AcompanhamentoDao();
        acompanhamento = new Acompanhamento();
        AcompanhamentoList = new ArrayList<Acompanhamento>();
        
    }
    
    public String salva() {
        System.out.println("tcc = "+getAcompanhamento().getTcc());
        acompanhamentoDAO.inserirAcompanhamento(getAcompanhamento());
        return "main";
    }
    
    public String editar() {
        acompanhamentoDAO.alterarAcompanhamento(acompanhamento);
        return "main";
    }
    
    public List<Acompanhamento> getAcompanhamentoList() {
        return acompanhamentoDAO.getAcompanhamentoList();
    }
    
    public List<Acompanhamento> getAcompanhamentoList(TCC tcc) {
        return acompanhamentoDAO.getAcompanhamentoList(tcc);
    }
    
    public String remove(Acompanhamento acompanhamento) {
        acompanhamentoDAO.deletarAcompanhamento(acompanhamento);
        return "main";
    }

    public Acompanhamento getAcompanhamento() {
        return acompanhamento;
    }

    public void setAcompanhamento(Acompanhamento acompanhamento) {
        this.acompanhamento = acompanhamento;
    }
    
    public String listarAcompanhamento() {
        return "acompanhamento_list";
    }
    
    public String novoAcompanhamento() {
        this.acompanhamento = new Acompanhamento();
        return "acompanhamento_novo";
    }
}

ifpe-20151-dsw3-projeto/web/paginas/acompanhamento/editar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        <link href="#{request.contextPath}/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="#{request.contextPath}/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
        <h:panelGroup id="leftcol" layout="block">
            <h:form>
                <h3><h:outputText value="Menu" /></h3>
                <br/>
                <h:commandLink action="#{AcompanhamentoMB.listarAcompanhamento}" value="Voltar"/>
            </h:form>
        </h:panelGroup>
        <h:panelGroup id="rightcol" layout="block">
            <h:form id="registerForm" styleClass="smart-green">
                <h3>Alterar dados</h3>

                <h:panelGrid columns="3" styleClass="formPanel">

                    <h:outputLabel for="tcc">
                        <h:outputText value="TCC"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="tcc" value="#{AcompanhamentoMB.acompanhamento.tcc}" converter="generic">
                        <f:selectItems value="#{TCCMB.TCCList}" var="tcc"
                                       itemLabel="#{tcc.titulo}" itemValue="#{tcc}" />
                    </h:selectOneMenu>
                    <h:message for="tcc" style="color:red" />

                    <h:outputLabel for="data">
                        <h:outputText value="Data"/>
                    </h:outputLabel>
                    <h:inputText id="data" required="true"
                                 value="#{AcompanhamentoMB.acompanhamento.data}" >
                        <f:convertDateTime type="date" dateStyle="short" pattern="dd/MM/yyyy"/>
                    </h:inputText>
                    <h:message for="data" style="color:red" />

                    <h:outputLabel for="horarioinicio">
                        <h:outputText value="Hotario Início:"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="horarioinicio" value="#{AcompanhamentoMB.acompanhamento.horarioInicio}" >
                        <f:selectItem itemLabel="07:00" itemValue="07:00"/>
                        <f:selectItem itemLabel="08:00" itemValue="08:00"/>
                        <f:selectItem itemLabel="09:00" itemValue="09:00"/>
                        <f:selectItem itemLabel="10:00" itemValue="10:00"/>
                        <f:selectItem itemLabel="11:00" itemValue="11:00"/>
                        <f:selectItem itemLabel="12:00" itemValue="12:00"/>
                        <f:selectItem itemLabel="13:00" itemValue="13:00"/>
                        <f:selectItem itemLabel="14:00" itemValue="14:00"/>
                        <f:selectItem itemLabel="15:00" itemValue="15:00"/>
                        <f:selectItem itemLabel="16:00" itemValue="16:00"/>
                        <f:selectItem itemLabel="17:00" itemValue="17:00"/>
                        <f:selectItem itemLabel="18:00" itemValue="18:00"/>
                        <f:selectItem itemLabel="19:00" itemValue="19:00"/>
                        <f:selectItem itemLabel="20:00" itemValue="20:00"/>
                        <f:selectItem itemLabel="21:00" itemValue="21:00"/>
                        <f:selectItem itemLabel="22:00" itemValue="22:00"/>
                        <f:convertDateTime type="time" dateStyle="short" pattern="HH:mm" />
                    </h:selectOneMenu>
                    <h:message for="horarioinicio" style="color:red" />

                    <h:outputLabel for="horariotermino">
                        <h:outputText value="Hotario Termino:"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="horariotermino" value="#{AcompanhamentoMB.acompanhamento.horarioTermino}" >
                        <f:selectItem itemLabel="07:00" itemValue="07:00"/>
                        <f:selectItem itemLabel="08:00" itemValue="08:00"/>
                        <f:selectItem itemLabel="09:00" itemValue="09:00"/>
                        <f:selectItem itemLabel="10:00" itemValue="10:00"/>
                        <f:selectItem itemLabel="11:00" itemValue="11:00"/>
                        <f:selectItem itemLabel="12:00" itemValue="12:00"/>
                        <f:selectItem itemLabel="13:00" itemValue="13:00"/>
                        <f:selectItem itemLabel="14:00" itemValue="14:00"/>
                        <f:selectItem itemLabel="15:00" itemValue="15:00"/>
                        <f:selectItem itemLabel="16:00" itemValue="16:00"/>
                        <f:selectItem itemLabel="17:00" itemValue="17:00"/>
                        <f:selectItem itemLabel="18:00" itemValue="18:00"/>
                        <f:selectItem itemLabel="19:00" itemValue="19:00"/>
                        <f:selectItem itemLabel="20:00" itemValue="20:00"/>
                        <f:selectItem itemLabel="21:00" itemValue="21:00"/>
                        <f:selectItem itemLabel="22:00" itemValue="22:00"/>
                        <f:convertDateTime type="time" dateStyle="short" pattern="HH:mm" />
                    </h:selectOneMenu>
                    <h:message for="horariotermino" style="color:red" />
                    
                    <h:outputLabel for="descricao">
                        <h:outputText value="Descricao"/>
                    </h:outputLabel>
                    <h:inputTextarea id="descricao" value="#{AcompanhamentoMB.acompanhamento.descricao}" cols="30" rows="5" />
                    <h:message for="resumo" style="color:red" />

                    <h:commandButton id="register" styleClass="button" 
                                     action="#{AcompanhamentoMB.editar()}"
                                     value="Alterar"
                                     />
                </h:panelGrid>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

ifpe-20151-dsw3-projeto/web/paginas/acompanhamento/lista.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Cadastro de Acompanhamento</title>
        <link href="#{request.contextPath}/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="#{request.contextPath}/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>

        <h:panelGroup id="leftcol" layout="block">
            <h:form>
                <h2><h:outputText value="Menu" /></h2>

                <br/>
                <h:commandLink action="#{AcompanhamentoMB.listarAcompanhamento}" value="Acompanhamanto"/>

                <br/>
                <h:commandLink action="#{AlunoControle.listarAluno}" value="Aluno"/>

                <br/>
                <h:commandLink action="#{ProfessorMB.listarProfessor()}" value="Professor"/>

                <br/>
                <h:commandLink action="#{TCCMB.listarTCC}" value="TCC"/>

                <br/>
                <h:commandLink action="#{TurmaMB.listarTurma}" value="Turma"/>

            </h:form>
        </h:panelGroup>
        <h:panelGroup id="rightcol" layout="block">

            <h3>Listagem de Acompanhamentos</h3>

            <h:form>
                <h:messages id="acompanhamentoMessages" showDetail="true" layout="table" styleClass="errorMessages"/>
                <h:dataTable id="tabelaDados" styleClass="tableData" border="1" value="#{AcompanhamentoMB.acompanhamentoList}" var="acompanhamentoReturn">
                    <h:column>
                        <f:facet name="header">
                            <h:commandLink action="#{AcompanhamentoMB.novoAcompanhamento}" value="Novo"/>
                        </f:facet>
                        <h:panelGroup>
                            <h:commandButton action="edit_acompanhamento" value="Editar">
                                <f:setPropertyActionListener target="#{AcompanhamentoMB.acompanhamento}"
                                                             value="#{acompanhamentoReturn}" />
                            </h:commandButton>
                            <h:commandButton onclick="if (!confirm('Tem certeza que deseja excluir o acompanhamento do #{acompanhamentoReturn.tcc.titulo}? '))
                                        return false;" action="#{AcompanhamentoMB.remove(acompanhamentoReturn)}" value="Apagar">
                            </h:commandButton>
                        </h:panelGroup>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Nome"/>
                        </f:facet>
                        <h:outputText value="#{acompanhamentoReturn.tcc.titulo}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Data"/>
                        </f:facet>
                        <h:outputText value="#{acompanhamentoReturn.data}">
                            <f:convertDateTime type="date" pattern="dd/MM/yyyy" />
                        </h:outputText>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Horário Início"/>
                        </f:facet>
                        <h:outputText value="#{acompanhamentoReturn.horarioInicio}">
                            <f:convertDateTime type="time" dateStyle="short" pattern="HH:mm" />
                        </h:outputText>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Horário Término"/>
                        </f:facet>
                        <h:outputText value="#{acompanhamentoReturn.horarioTermino}">
                            <f:convertDateTime type="time" dateStyle="short" pattern="HH:mm" />
                        </h:outputText>
                    </h:column>
                    
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Nome"/>
                        </f:facet>
                        <h:outputText value="#{acompanhamentoReturn.descricao}"/>
                    </h:column>

                </h:dataTable>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

ifpe-20151-dsw3-projeto/web/paginas/acompanhamento/novo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Acompanhamento Cadastro</title>
        <link href="#{request.contextPath}/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="#{request.contextPath}/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
        <h:panelGroup id="leftcol" layout="block">
            <h:form>
                <h3><h:outputText value="Menu" /></h3>
                <br/>
                <h:commandLink action="#{AcompanhamentoMB.listarAcompanhamento}" value="Voltar"/>
            </h:form>
        </h:panelGroup>
        <h:panelGroup id="rightcol" layout="block">

            <h3>Cadastrar Acompanhamento</h3>

            <h:form id="registerForm" styleClass="smart-green">

                <h:panelGrid columns="3" styleClass="formPanel">

                    <h:outputLabel for="tcc">
                        <h:outputText value="TCC"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="tcc" value="#{AcompanhamentoMB.acompanhamento.tcc}" converter="generic">  
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItems value="#{TCCMB.TCCList}" var="tcc"
                                       itemLabel="#{tcc.titulo}" itemValue="#{tcc}" />
                    </h:selectOneMenu>
                    <h:message for="tcc" style="color:red" />

                    <h:outputLabel for="data">
                        <h:outputText value="Data"/>
                    </h:outputLabel>
                    <h:inputText id="data" required="true"
                                 value="#{AcompanhamentoMB.acompanhamento.data}" >
                        <f:convertDateTime type="date" dateStyle="short" pattern="dd/MM/yyyy"/>
                    </h:inputText>
                    <h:message for="data" style="color:red" />

                    <h:outputLabel for="horarioinicio">
                        <h:outputText value="Hotario Início:"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="horarioinicio" value="#{AcompanhamentoMB.acompanhamento.horarioInicio}" >
                        <f:selectItem itemLabel="07:00" itemValue="07:00"/>
                        <f:selectItem itemLabel="08:00" itemValue="08:00"/>
                        <f:selectItem itemLabel="09:00" itemValue="09:00"/>
                        <f:selectItem itemLabel="10:00" itemValue="10:00"/>
                        <f:selectItem itemLabel="11:00" itemValue="11:00"/>
                        <f:selectItem itemLabel="12:00" itemValue="12:00"/>
                        <f:selectItem itemLabel="13:00" itemValue="13:00"/>
                        <f:selectItem itemLabel="14:00" itemValue="14:00"/>
                        <f:selectItem itemLabel="15:00" itemValue="15:00"/>
                        <f:selectItem itemLabel="16:00" itemValue="16:00"/>
                        <f:selectItem itemLabel="17:00" itemValue="17:00"/>
                        <f:selectItem itemLabel="18:00" itemValue="18:00"/>
                        <f:selectItem itemLabel="19:00" itemValue="19:00"/>
                        <f:selectItem itemLabel="20:00" itemValue="20:00"/>
                        <f:selectItem itemLabel="21:00" itemValue="21:00"/>
                        <f:selectItem itemLabel="22:00" itemValue="22:00"/>
                        <f:convertDateTime type="time" dateStyle="short" pattern="HH:mm" />
                    </h:selectOneMenu>
                    <h:message for="horarioinicio" style="color:red" />

                    <h:outputLabel for="horariotermino">
                        <h:outputText value="Hotario Termino:"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="horariotermino" value="#{AcompanhamentoMB.acompanhamento.horarioTermino}" >
                        <f:selectItem itemLabel="07:00" itemValue="07:00"/>
                        <f:selectItem itemLabel="08:00" itemValue="08:00"/>
                        <f:selectItem itemLabel="09:00" itemValue="09:00"/>
                        <f:selectItem itemLabel="10:00" itemValue="10:00"/>
                        <f:selectItem itemLabel="11:00" itemValue="11:00"/>
                        <f:selectItem itemLabel="12:00" itemValue="12:00"/>
                        <f:selectItem itemLabel="13:00" itemValue="13:00"/>
                        <f:selectItem itemLabel="14:00" itemValue="14:00"/>
                        <f:selectItem itemLabel="15:00" itemValue="15:00"/>
                        <f:selectItem itemLabel="16:00" itemValue="16:00"/>
                        <f:selectItem itemLabel="17:00" itemValue="17:00"/>
                        <f:selectItem itemLabel="18:00" itemValue="18:00"/>
                        <f:selectItem itemLabel="19:00" itemValue="19:00"/>
                        <f:selectItem itemLabel="20:00" itemValue="20:00"/>
                        <f:selectItem itemLabel="21:00" itemValue="21:00"/>
                        <f:selectItem itemLabel="22:00" itemValue="22:00"/>
                        <f:convertDateTime type="time" dateStyle="short" pattern="HH:mm" />
                    </h:selectOneMenu>
                    <h:message for="horariotermino" style="color:red" />
                    
                    <h:outputLabel for="descricao">
                        <h:outputText value="Descricao"/>
                    </h:outputLabel>
                    <h:inputTextarea id="descricao" value="#{AcompanhamentoMB.acompanhamento.descricao}" cols="30" rows="5" />
                    <h:message for="resumo" style="color:red" />

                    <h:commandButton id="register" styleClass="button" 
                                     action="#{AcompanhamentoMB.salva()}"
                                     value="Adicionar"
                                     />
                </h:panelGrid>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>