ifpe-20151-dsw3-projeto/src/java/jsf/AlunoMB.java
package jsf;

/**
 *
 * @author João Henrique 2
 */
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import jpa.entidades.Aluno;
import jpa.controle.AlunoDao;

@ManagedBean(name = "AlunoMB")
@SessionScoped
public class AlunoMB implements Serializable{

    private AlunoDao alunoDAO;
    private Aluno aluno;
    private List<Aluno> AlunoList;
    
    public AlunoMB(){
        
        alunoDAO = new AlunoDao();
        aluno = new Aluno();
        AlunoList = new ArrayList<Aluno>();
        
    }
    
    public String salva() {
        
        System.out.println("nome = "+getAluno().getNome());
        alunoDAO.inserirAluno(getAluno());
        
        return "main";
    }
    
    public String editar() {
        
        alunoDAO.alterarAluno(aluno);
        
        return "main";
    }
    
    public List<Aluno> getAlunoList() {
        
        return alunoDAO.getAlunoList();
        
    }
    
    public String remove(Aluno aluno) {
        
        alunoDAO.deletarAluno(aluno);
        
        return "main";
    }

    public Aluno getAluno() {
        return aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    
    public String listarAluno() {
        return "aluno_list";
    }
    
    public String novoAluno() {
        this.aluno = new Aluno();
        return "aluno_novo";
    }
}

ifpe-20151-dsw3-projeto/src/java/jsf/ProfessorMB.java
package jsf;

/**
 *
 * @author João Henrique 2
 */
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import jpa.entidades.Professor;
import jpa.controle.ProfessorDao;

@ManagedBean(name = "ProfessorMB")
@SessionScoped
public class ProfessorMB implements Serializable{

    private ProfessorDao professorDAO = new ProfessorDao();
    private Professor professor = new Professor();
    
    private List<Professor> ProfessorList = null;
    
    public ProfessorMB(){
        
        ProfessorList = new ArrayList<Professor>();
        
    }
    
    public String salva() {
        
        System.out.println("id = "+getProfessor().getId());
        professorDAO.inserirProfessor(getProfessor());
        
        return "main";
    }
    
    public String editar() {
        
        professorDAO.alterarProfessor(professor);
        
        return "main";
    }
    
    public List<Professor> getProfessorList() {
        
        return professorDAO.getProfessorList();
        
    }
    
    public String remove(Professor professor) {
        
        professorDAO.deletarProfessor(professor);
        
        return "main";
    }

    public Professor getProfessor() {
        return professor;
    }

    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    
    public String listarProfessor() {
        return "professor_list";
    }
    
    public String novoProfessor() {
        this.professor = new Professor();
        return "professor_novo";
    }
}

ifpe-20151-dsw3-projeto/src/java/jsf/TurmaMB.java
package jsf;

/**
 *
 * @author João Henrique 2
 */
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import jpa.entidades.Turma;
import jpa.controle.TurmaDao;
import jpa.entidades.Aluno;

@ManagedBean(name = "TurmaMB")
@SessionScoped
public class TurmaMB implements Serializable {

    private TurmaDao turmaDAO;
    private Turma turma;

    private List<Turma> TurmaList = null;

    public TurmaMB() {
        
    turmaDAO = new TurmaDao();
    turma = new Turma();
    TurmaList  = new ArrayList<Turma>();

}

public String salva() {
        
        turmaDAO.inserirTurma(getTurma());
        
        return "main";
    }
    
    public String editar() {
        
        turmaDAO.alterarTurma(turma);
        
        return "main";
    }
    
    public List<Turma> getTurmaList() {
        TurmaList = null;
        TurmaList = turmaDAO.getTurmaList();
        return TurmaList;
    }
    
    public List<Aluno> getAlunoTurmaList(Turma turma) {
        return turmaDAO.getAlunosTurmaList(turma);
    }
    
    public String remove(Turma turma) {
        
        turmaDAO.deletarTurma(turma);
        
        return "main";
    }

    public Turma getTurma() {
        return turma;
    }

    public void setTurma(Turma turma) {
        this.turma = turma;
    }
    
    public String listarTurma() {
        return "turma_list";
    }
    
    public String novoTurma() {
        this.turma = new Turma();
        return "turma_novo";
    }
}

ifpe-20151-dsw3-projeto/web/paginas/aluno/editar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        <link href="#{request.contextPath}/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="#{request.contextPath}/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
        <h:panelGroup id="leftcol" layout="block">
            <h:form>
                <h3><h:outputText value="Menu" /></h3>
                <br/>
                <h:commandLink action="#{AlunoControle.listarAluno}" value="Voltar"/>
            </h:form>
        </h:panelGroup>
        <h:panelGroup id="rightcol" layout="block">
            <h:form id="registerForm" styleClass="smart-green">
                <h3>Alterar dados</h3>

                <h:panelGrid columns="3" styleClass="formPanel">

                    <h:outputLabel for="nome">
                        <h:outputText value="Nome:"/>
                    </h:outputLabel>
                    <h:inputText id="nome" value="#{AlunoMB.aluno.nome}" required="true" 
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="nome" style="color:red" />

                    <h:outputLabel for="dataNascimento">
                        <h:outputText value="Data de Nascimento:"/>
                    </h:outputLabel>
                    <h:inputText id="dataNascimento" required="true"
                                 value="#{AlunoMB.aluno.dataNascimento}">
                        <f:convertDateTime pattern="dd/MM/yyyy"/> 
                    </h:inputText>
                    <h:message for="dataNascimento" style="color:red" />

                    <h:outputLabel for="email">
                        <h:outputText value="E-mail:"/>
                    </h:outputLabel>
                    <h:inputText id="email" value="#{AlunoMB.aluno.email}" required="true" 
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="email" style="color:red" />

                    <h:outputLabel for="matricula">
                        <h:outputText value="Matricula:"/>
                    </h:outputLabel>
                    <h:inputText id="matricula" value="#{AlunoMB.aluno.matricula}" required="true"
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="matricula" style="color:red" />
                    
                    <h:outputLabel for="turma">
                        <h:outputText value="Turma"/>
                    </h:outputLabel>
                    <h:selectOneMenu value="#{AlunoMB.aluno.turma}"  converter="generic">
                        <f:selectItems value="#{TurmaMB.turmaList}" var="turma"
                                       itemLabel="#{turma.codigo}" itemValue="#{turma}" />
                    </h:selectOneMenu>
                    <h:message for="turma" style="color:red" />

                    <h:outputLabel for="orientador">
                        <h:outputText value="Orientador"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="orientador" value="#{AlunoMB.aluno.orientador}" converter="generic">
                        <f:selectItems value="#{ProfessorMB.professorList}" var="orientador" 
                                       itemLabel="#{orientador.nome}" itemValue="#{orientador}"  />
                    </h:selectOneMenu>
                    <h:message for="orientador" style="color:red" />

                    <h:outputLabel for="status">
                        <h:outputText value="Status:"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="status" value="#{AlunoMB.aluno.status}" required="true" requiredMessage="Campo obrigatório!">
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItem itemLabel="MATRICULADO" itemValue="1"/>  
                        <f:selectItem itemLabel="DESISTENTE" itemValue="2"/>
                        <f:selectItem itemLabel="GRADUADO" itemValue="3"/>  
                    </h:selectOneMenu>
                    <h:message for="status" style="color:red" />

                    <h:commandButton id="register" styleClass="button" 
                                     action="#{AlunoMB.editar()}"
                                     value="Alterar"
                                     />
                </h:panelGrid>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

ifpe-20151-dsw3-projeto/web/paginas/aluno/lista.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Cadastro de Aluno</title>
        <link href="#{request.contextPath}/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="#{request.contextPath}/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>

        <h:panelGroup id="leftcol" layout="block">
            <h:form>
                <h2><h:outputText value="Menu" /></h2>

                <br/>
                <h:commandLink action="#{AcompanhamentoMB.listarAcompanhamento}" value="Acompanhamanto"/>

                <br/>
                <h:commandLink action="#{AlunoMB.listarAluno}" value="Aluno"/>

                <br/>
                <h:commandLink action="#{ProfessorMB.listarProfessor()}" value="Professor"/>

                <br/>
                <h:commandLink action="#{TCCMB.listarTCC}" value="TCC"/>

                <br/>
                <h:commandLink action="#{TurmaMB.listarTurma}" value="Turma"/>

            </h:form>
        </h:panelGroup>
        <h:panelGroup id="rightcol" layout="block">

            <h3>Listagem de Alunos</h3>

            <h:form>
                <h:messages id="alunoMessages" showDetail="true" layout="table" styleClass="errorMessages"/>
                <h:dataTable id="tabelaDados" styleClass="tableData" border="1" value="#{AlunoMB.alunoList}" var="alunoReturn">
                    <h:column>
                        <f:facet name="header">
                            <h:commandLink action="#{AlunoMB.novoAluno}" value="Novo"/>
                        </f:facet>
                        <h:panelGroup>
                            <h:commandButton action="edit_aluno" value="Editar">
                                <f:setPropertyActionListener target="#{AlunoMB.aluno}"
                                                             value="#{alunoReturn}" />
                            </h:commandButton>
                            <h:commandButton onclick="if (!confirm('Tem certeza que deseja excluir o aluno #{alunoReturn.nome}? '))
                                        return false;" action="#{AlunoMB.remove(alunoReturn)}" value="Apagar">
                            </h:commandButton>
                        </h:panelGroup>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Nome"/>
                        </f:facet>
                        <h:outputText value="#{alunoReturn.nome}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Data da Nascimento"/>
                        </f:facet>
                        <h:outputText value="#{alunoReturn.dataNascimento}">
                            <f:convertDateTime type="date" pattern="dd/MM/yyyy" />
                        </h:outputText>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="E-mail"/>
                        </f:facet>
                        <h:outputText value="#{alunoReturn.email}">
                        </h:outputText>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Matricula"/>
                        </f:facet>
                        <h:outputText value="#{alunoReturn.matricula}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Turma"/>
                        </f:facet>
                        <h:outputText value="#{alunoReturn.turma.codigo}">
                        </h:outputText>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Status"/>
                        </f:facet>
                        <h:outputText value="Matriculado" rendered="#{alunoReturn.status==1}" />    
                        <h:outputText value="Desistente" rendered="#{alunoReturn.status==2}" />    
                        <h:outputText value="Graduado" rendered="#{alunoReturn.status==3}" />
                    </h:column>

                </h:dataTable>

            </h:form>
        </h:panelGroup>
    </h:body>
</html>

ifpe-20151-dsw3-projeto/web/paginas/aluno/novo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Aluno Cadastro</title>
        <link href="#{request.contextPath}/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="#{request.contextPath}/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>

        <h:panelGroup id="leftcol" layout="block">
            <h:form>
                <h3><h:outputText value="Menu" /></h3>
                <br/>
                <h:commandLink action="#{AlunoControle.listarAluno}" value="Voltar"/>
            </h:form>
        </h:panelGroup>
        <h:panelGroup id="rightcol" layout="block">

            <h3>Cadastrar Aluno</h3>

            <h:form id="registerForm" styleClass="smart-green">            

                <h:panelGrid columns="3" styleClass="formPanel">

                    <h:outputLabel for="nome">
                        <h:outputText value="Nome:"/>
                    </h:outputLabel>
                    <h:inputText id="nome" value="#{AlunoMB.aluno.nome}" required="true" requiredMessage="Campo obrigatório!"
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="nome" style="color:red" />

                    <h:outputLabel for="dataNascimento">
                        <h:outputText value="Data de Nascimento"/>
                    </h:outputLabel>
                    <h:inputText id="dataNascimento" required="true" requiredMessage="Campo obrigatório!"
                                 value="#{AlunoMB.aluno.dataNascimento}" >
                        <f:convertDateTime type="date" dateStyle="short" pattern="dd/MM/yyyy"/> 
                    </h:inputText>
                    <h:message for="dataNascimento" style="color:red" />

                    <h:outputLabel for="email">
                        <h:outputText value="E-mail:"/>
                    </h:outputLabel>
                    <h:inputText id="email" value="#{AlunoMB.aluno.email}" required="true" requiredMessage="Campo obrigatório!" >
                        <f:validator validatorId="validadorEmail" />
                    </h:inputText>
                    <h:message for="email" style="color:red" />

                    <h:outputLabel for="matricula">
                        <h:outputText value="Matricula:"/>
                    </h:outputLabel>
                    <h:inputText id="matricula" value="#{AlunoMB.aluno.matricula}" required="true" requiredMessage="Campo obrigatório!"
                                 validatorMessage="Valor inválido.">
                        <f:validateRegex pattern="(\w{7}-\w{6})" />
                        <f:validator validatorId="validadorMatricula" />
                    </h:inputText>
                    <h:message for="matricula" style="color:red" />
                    

                    <h:outputLabel for="turma">
                        <h:outputText value="Turma"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="turma" value="#{AlunoMB.aluno.turma}" converter="generic" required="true" requiredMessage="Campo obrigatório!">  
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItems value="#{TurmaMB.turmaList}" var="turma"
                                       itemLabel="#{turma.codigo}" itemValue="#{turma}" />
                    </h:selectOneMenu>
                    <h:message for="turma" style="color:red" />

                    <h:outputLabel for="orientador">
                        <h:outputText value="Orientador"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="orientador" value="#{AlunoMB.aluno.orientador}" converter="generic" required="true" requiredMessage="Campo obrigatório!">  
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItems value="#{ProfessorMB.professorList}" var="orientador" 
                                       itemLabel="#{orientador.nome}" itemValue="#{orientador}"  />
                    </h:selectOneMenu>
                    <h:message for="orientador" style="color:red" />

                    <h:outputLabel for="status">
                        <h:outputText value="Status:"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="status" value="#{AlunoMB.aluno.status}" required="true" requiredMessage="Campo obrigatório!">
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItem itemLabel="MATRICULADO" itemValue="1"/>  
                        <f:selectItem itemLabel="DESISTENTE" itemValue="2"/>
                        <f:selectItem itemLabel="GRADUADO" itemValue="3"/>  
                    </h:selectOneMenu>
                    <h:message for="status" style="color:red" />

                    <h:commandButton id="register" styleClass="button" 
                                     action="#{AlunoMB.salva()}"
                                     value="Adicionar"
                                     />
                </h:panelGrid>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>