ifpe-20151-dsw3-projeto/src/java/jsf/AlunoMB.java
package jsf;

/**
 *
 * @author João Henrique 2
 */
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import jpa.entidades.Aluno;
import jpa.controle.AlunoDao;

@ManagedBean(name = "AlunoMB")
@SessionScoped
public class AlunoMB implements Serializable{

    private AlunoDao alunoDAO;
    private Aluno aluno;
    private List<Aluno> AlunoList;
    
    public AlunoMB(){
        
        alunoDAO = new AlunoDao();
        aluno = new Aluno();
        AlunoList = new ArrayList<Aluno>();
        
    }
    
    public String salva() {
        
        System.out.println("nome = "+getAluno().getNome());
        alunoDAO.inserirAluno(getAluno());
        
        return "main";
    }
    
    public String editar() {
        
        alunoDAO.alterarAluno(aluno);
        
        return "main";
    }
    
    public List<Aluno> getAlunoList() {
        
        return alunoDAO.getAlunoList();
        
    }
    
    public String remove(Aluno aluno) {
        
        alunoDAO.deletarAluno(aluno);
        
        return "main";
    }

    public Aluno getAluno() {
        return aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    
    public String listarAluno() {
        return "aluno_list";
    }
    
    public String novoAluno() {
        this.aluno = new Aluno();
        return "aluno_novo";
    }
}

ifpe-20151-dsw3-projeto/src/java/jsf/TCCMB.java
package jsf;

/**
 *
 * @author João Henrique 2
 */
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import jpa.entidades.TCC;
import jpa.controle.TCCDao;
import jpa.entidades.Acompanhamento;
import jsf.AcompanhamentoMB;
import jpa.entidades.AreaConhecimento;

@ManagedBean(name = "TCCMB")
@SessionScoped
public class TCCMB implements Serializable {

    private TCCDao tccDAO;
    private TCC tcc;
    private List<TCC> TCCList;
    private List<AreaConhecimento> areaList;
    private AreaConhecimento area;
    private AcompanhamentoMB acompanhamentoMB;
    private List<Acompanhamento> acompanhamentoList;

    public TCCMB() {
        tccDAO = new TCCDao();
        tcc = new TCC();
        TCCList = new ArrayList<TCC>();
    }

    public String salva() {
        tcc.addArea(area);
        tccDAO.inserirTCC(getTCC());
        return "main";
    }

    public String editar() {
        tccDAO.alterarTCC(tcc);
        return "main";
    }

    public List<TCC> getTCCList() {
        return tccDAO.getTCCList();
    }

    public List<AreaConhecimento> getGrandeAreaList() {
        areaList = tccDAO.getGrandeAreaList();
        return areaList;
    }

    public List<AreaConhecimento> getAreaList(int grandeArea) {
        areaList = tccDAO.getAreaList(grandeArea);
        return areaList;
    }

    public List<AreaConhecimento> getSubAreaList(int grandeArea, int area) {
        areaList = tccDAO.getSubAreaList(grandeArea, area);
        return areaList;
    }

    public List<AreaConhecimento> getAreaEspList(int grandeArea, int area, int subarea) {
        areaList = tccDAO.getAreaEspList(grandeArea, area, subarea);
        return areaList;
    }

    public List<AreaConhecimento> getAreaConhecimentoList() {
        return areaList;
    }

    public AreaConhecimento getArea() {
        return area;
    }

    public void setArea(AreaConhecimento area) {
        this.area = area;
    }

    public String remove(TCC tcc) {
        tccDAO.deletarTCC(tcc);
        return "main";
    }

    public TCC getTCC() {
        return tcc;
    }

    public void setTCC(TCC tcc) {
        this.tcc = tcc;
    }

    public String listarTCC() {
        return "tcc_list";
    }

    public String novoTCC() {
        this.tcc = new TCC();
        return "tcc_novo";
    }
}

ifpe-20151-dsw3-projeto/web/paginas/tcc/editar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        <link href="#{request.contextPath}/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="#{request.contextPath}/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
        <h:panelGroup id="leftcol" layout="block">
            <h:form>
                <h3><h:outputText value="Menu" /></h3>
                <br/>
                <h:commandLink action="#{TCCMB.listarTCC}" value="Voltar"/>

            </h:form>
        </h:panelGroup>
        <h:panelGroup id="rightcol" layout="block">
            <h:form id="registerForm" styleClass="smart-green">
                <h3>Alterar dados</h3>

                <h:panelGrid columns="3" styleClass="formPanel">
                    <h:outputLabel for="titulo">
                        <h:outputText value="Título:"/>
                    </h:outputLabel>
                    <h:inputText id="titulo" value="#{TCCMB.TCC.titulo}" required="true" 
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="titulo" style="color:red" />

                    <h:outputLabel for="status">
                        <h:outputText value="Status:"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="status" value="#{TCCMB.TCC.status}" required="true" requiredMessage="Campo obrigatório!">
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItem itemLabel="ATIVO" itemValue="1"/>
                        <f:selectItem itemLabel="INATIVO" itemValue="2"/>
                        <f:selectItem itemLabel="PUBLICADO" itemValue="3"/>  
                    </h:selectOneMenu>
                    <h:message for="status" style="color:red" />

                    <h:outputLabel for="aluno">
                        <h:outputText value="Aluno"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="aluno" value="#{TCCMB.TCC.aluno}" converter="generic" required="true">
                        <f:selectItems value="#{AlunoMB.alunoList}" var="aluno"
                                       itemLabel="#{aluno.nome}" itemValue="#{aluno}" />
                    </h:selectOneMenu>
                    <h:message for="aluno" style="color:red" />

                    <h:outputLabel for="dataInicio">
                        <h:outputText value="Data de Inicio"/>
                    </h:outputLabel>
                    <h:inputText id="dataInicio" required="true"
                                 value="#{TCCMB.TCC.dataInicio}" >
                        <f:convertDateTime type="date" dateStyle="short" pattern="dd/MM/yyyy"/> 
                    </h:inputText>
                    <h:message for="dataInicio" style="color:red" />

                    <h:outputLabel for="resumo">
                        <h:outputText value="Resumo:"/>
                    </h:outputLabel>
                    <h:inputTextarea id="resumo" value="#{TCCMB.TCC.resumo}" cols="30" rows="10" />
                    <h:message for="resumo" style="color:red" />

                    <h:outputLabel for="grande_area">
                        <h:outputText value="Grande Area"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="grandearea" value="#{TCCMB.area}" converter="generic" >  
                        <f:selectItem itemLabel="Selecione" noSelectionOption="true" />
                        <f:selectItems value="#{TCCMB.grandeAreaList}" 
                                       var="grande_area" 
                                       itemLabel="#{grande_area.titulo}" 
                                       itemValue="#{grande_area}" />
                        <f:ajax render="area" event="change" listener="#{TCCMB.getAreaList(TCCMB.area.grandeArea)}"/>
                    </h:selectOneMenu>
                    <h:message for="grandearea" style="color:red" />

                    <h:outputLabel for="area">
                        <h:outputText value="Area"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="area" value="#{TCCMB.area}" converter="generic" >
                        <f:selectItem itemLabel="Selecione" noSelectionOption="true" />
                        <f:selectItems value="#{TCCMB.getAreaList(TCCMB.area.grandeArea)}" 
                                       var="area" 
                                       itemLabel="#{area.titulo}" 
                                       itemValue="#{area}" />
                        <f:ajax render="subarea" event="change" listener="#{TCCMB.getSubAreaList(TCCMB.area.grandeArea,TCCMB.area.area)}"/>
                    </h:selectOneMenu>
                    <h:message for="area" style="color:red" />

                    <h:outputLabel for="subarea">
                        <h:outputText value="Sub Area"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="subarea" value="#{TCCMB.area}" converter="generic" >
                        <f:selectItem itemLabel="Selecione" itemValue="" noSelectionOption="true"/>
                        <f:selectItems value="#{TCCMB.getSubAreaList(TCCMB.area.grandeArea,TCCMB.area.area)}" 
                                       var="subarea" 
                                       itemLabel="#{subarea.titulo}" 
                                       itemValue="#{subarea}" />
                        <f:ajax render="areaesp" event="change" listener="#{TCCMB.getAreaEspList(TCCMB.area.grandeArea, TCCMB.area.area, TCCMB.area.subArea)}"/>
                    </h:selectOneMenu>
                    <h:message for="subarea" style="color:red" />

                    <h:outputLabel for="areaesp">
                        <h:outputText value="Area Específica"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="areaesp" value="#{TCCMB.area}" converter="generic" required="true" >
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItems value="#{TCCMB.getAreaEspList(TCCMB.area.grandeArea, TCCMB.area.area, TCCMB.area.subArea)}" 
                                       var="areaesp" 
                                       itemLabel="#{areaesp.titulo}" 
                                       itemValue="#{areaesp}" />
                    </h:selectOneMenu>
                    <h:message for="areaesp" style="color:red" />

                    <h:outputLabel for="avalexter">
                        <h:outputText value="Avaliador externo:"/>
                    </h:outputLabel>
                    <h:inputText id="avalexter" value="#{TCCMB.TCC.avaliadorExterno}"
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="avalexter" style="color:red" />

                    <h:outputLabel for="avalint">
                        <h:outputText value="Avaliador interno:"/>
                    </h:outputLabel>
                    <h:inputText id="avalint" value="#{TCCMB.TCC.avaliadorInterno}" 
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="avalint" style="color:red" />

                    <h:outputLabel for="dataDefesa">
                        <h:outputText value="Data da Defesa"/>
                    </h:outputLabel>
                    <h:inputText id="dataDefesa"
                                 value="#{TCCMB.TCC.dataDefesa}" >
                        <f:convertDateTime type="date" dateStyle="short" pattern="dd/MM/yyyy"/> 
                    </h:inputText>
                    <h:message for="dataDefesa" style="color:red" />

                    <h:outputLabel for="imprenta">
                        <h:outputText value="Imprenta:"/>
                    </h:outputLabel>
                    <h:inputText id="imprenta" value="#{TCCMB.TCC.imprenta}"
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="imprenta" style="color:red" />

                    <h:outputLabel for="nota">
                        <h:outputText value="Nota:"/>
                    </h:outputLabel>
                    <h:inputText id="nota" value="#{TCCMB.TCC.nota}" 
                                 validatorMessage="Valor inválido.">
                        <f:validateDoubleRange minimum="00.00" maximum="10.00" />
                    </h:inputText>
                    <h:message for="nota" style="color:red" />

                    <h:outputLabel for="statusdesafa">
                        <h:outputText value="Status da defesa:"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="statusdefesa" value="#{TCCMB.TCC.status}" >
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItem itemLabel="APROVADA" itemValue="1"/>  
                        <f:selectItem itemLabel="REPROVADA" itemValue="2"/>
                        <f:selectItem itemLabel="ADIADA" itemValue="2"/>
                    </h:selectOneMenu>
                    <h:message for="statusdefesa" style="color:red" />

                    <h:commandButton id="register" styleClass="button" 
                                     action="#{TCCMB.editar()}"
                                     value="Alterar"
                                     />
                </h:panelGrid>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

ifpe-20151-dsw3-projeto/web/paginas/tcc/lista.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Cadastro de TCC</title>
        <link href="#{request.contextPath}/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="#{request.contextPath}/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>

        <h:panelGroup id="leftcol" layout="block">
            <h:form>
                <h2><h:outputText value="Menu" /></h2>

                <br/>
                <h:commandLink action="#{AcompanhamentoMB.listarAcompanhamento}" value="Acompanhamanto"/>

                <br/>
                <h:commandLink action="#{AlunoControle.listarAluno}" value="Aluno"/>

                <br/>
                <h:commandLink action="#{ProfessorMB.listarProfessor()}" value="Professor"/>

                <br/>
                <h:commandLink action="#{TCCMB.listarTCC}" value="TCC"/>

                <br/>
                <h:commandLink action="#{TurmaMB.listarTurma}" value="Turma"/>

            </h:form>
        </h:panelGroup>
        <h:panelGroup id="rightcol" layout="block">

            <h3>Listagem de TCCs:</h3>

            <h:form>
                <h:messages id="tccMessages" showDetail="true" layout="table" styleClass="errorMessages"/>
                <h:dataTable id="tabelaDados" styleClass="tableData" border="1" value="#{TCCMB.TCCList}" var="tccReturn">
                    <h:column>
                        <f:facet name="header">
                            <h:commandLink action="#{TCCMB.novoTCC}" value="Novo"/>
                            <!--<h:commandButton action="tcc_novo" value="Novo"/>-->
                        </f:facet>
                        <h:panelGroup>
                            <h:commandButton action="edit_tcc" value="Editar">
                                <f:setPropertyActionListener target="#{TCCMB.TCC}"
                                                             value="#{tccReturn}" />
                            </h:commandButton>
                            <h:commandButton onclick="if (!confirm('Tem certeza que deseja excluir o tcc #{tccReturn.titulo}? '))
                                        return false;" action="#{TCCMB.remove(tccReturn)}" value="Apagar">
                            </h:commandButton>
                        </h:panelGroup>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Título"/>
                        </f:facet>
                        <h:outputText value="#{tccReturn.titulo}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Aluno"/>
                        </f:facet>
                        <h:outputText value="#{tccReturn.aluno.nome}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Orientador"/>
                        </f:facet>
                        <h:outputText value="#{tccReturn.aluno.orientador.nome}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Data da Defesa"/>
                        </f:facet>
                        <h:outputText value="#{tccReturn.dataDefesa}">
                            <f:convertDateTime type="date" pattern="dd/MM/yyyy" />
                        </h:outputText>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Data da Início"/>
                        </f:facet>
                        <h:outputText value="#{tccReturn.dataInicio}">
                            <f:convertDateTime type="date" pattern="dd/MM/yyyy" />
                        </h:outputText>
                    </h:column>

                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Imprenta"/>
                        </f:facet>
                        <h:outputText value="#{tccReturn.imprenta}"/>
                    </h:column>

                </h:dataTable>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

ifpe-20151-dsw3-projeto/web/paginas/tcc/novo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>TCC Cadastro</title>
        <link href="#{request.contextPath}/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="#{request.contextPath}/css/custom.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>

        <h:panelGroup id="leftcol" layout="block">
            <h:form>
                <h3><h:outputText value="Menu" /></h3>
                <br/>
                <h:commandLink action="#{TCCMB.listarTCC}" value="Voltar"/>

            </h:form>
        </h:panelGroup>
        <h:panelGroup id="rightcol" layout="block">

            <h3>Cadastrar TCC</h3>

            <h:form id="registerForm" styleClass="smart-green">

                <h:panelGrid columns="3" styleClass="formPanel">

                    <h:outputLabel for="titulo">
                        <h:outputText value="Título:"/>
                    </h:outputLabel>
                    <h:inputText id="titulo" value="#{TCCMB.TCC.titulo}" required="true" 
                                 validatorMessage="Valor inválido!">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="titulo" style="color:red" />

                    <h:outputLabel for="status">
                        <h:outputText value="Status:"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="status" value="#{TCCMB.TCC.status}" required="true" requiredMessage="Campo obrigatório!">
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItem itemLabel="ATIVO" itemValue="1"/>  
                        <f:selectItem itemLabel="INATIVO" itemValue="2"/>
                        <f:selectItem itemLabel="PUBLICADO" itemValue="3"/>  
                    </h:selectOneMenu>
                    <h:message for="status" style="color:red" />

                    <h:outputLabel for="aluno">
                        <h:outputText value="Aluno"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="aluno" value="#{TCCMB.TCC.aluno}" converter="generic" required="true">  
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItems value="#{AlunoMB.alunoList}" var="aluno" 
                                       itemLabel="#{aluno.nome}" itemValue="#{aluno}"  />
                    </h:selectOneMenu>
                    <h:message for="aluno" style="color:red" />

                    <h:outputLabel for="dataInicio">
                        <h:outputText value="Data de Inicio"/>
                    </h:outputLabel>
                    <h:inputText id="dataInicio" required="true"
                                 value="#{TCCMB.TCC.dataInicio}" >
                        <f:convertDateTime type="date" dateStyle="short" pattern="dd/MM/yyyy"/> 
                    </h:inputText>
                    <h:message for="dataInicio" style="color:red" />

                    <h:outputLabel for="resumo">
                        <h:outputText value="Resumo"/>
                    </h:outputLabel>
                    <h:inputTextarea value="#{TCCMB.TCC.resumo}" cols="30" rows="10" />
                    <h:message for="resumo" style="color:red" />

                    <h:outputLabel for="grande_area">
                        <h:outputText value="Grande Area"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="grandearea" value="#{TCCMB.area}" converter="generic" >  
                        <f:selectItem itemLabel="Selecione" noSelectionOption="true" />
                        <f:selectItems value="#{TCCMB.grandeAreaList}" 
                                       var="grande_area" 
                                       itemLabel="#{grande_area.titulo}" 
                                       itemValue="#{grande_area}" />
                        <f:ajax render="area" event="change" listener="#{TCCMB.getAreaList(TCCMB.area.grandeArea)}"/>
                    </h:selectOneMenu>
                    <h:message for="grandearea" style="color:red" />

                    <h:outputLabel for="area">
                        <h:outputText value="Area"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="area" value="#{TCCMB.area}" converter="generic" >
                        <f:selectItem itemLabel="Selecione" noSelectionOption="true" />
                        <f:selectItems value="#{TCCMB.getAreaList(TCCMB.area.grandeArea)}" 
                                       var="area" 
                                       itemLabel="#{area.titulo}" 
                                       itemValue="#{area}" />
                        <f:ajax render="subarea" event="change" listener="#{TCCMB.getSubAreaList(TCCMB.area.grandeArea,TCCMB.area.area)}"/>
                    </h:selectOneMenu>
                    <h:message for="area" style="color:red" />

                    <h:outputLabel for="subarea">
                        <h:outputText value="Sub Area"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="subarea" value="#{TCCMB.area}" converter="generic" >
                        <f:selectItem itemLabel="Selecione" itemValue="" noSelectionOption="true"/>
                        <f:selectItems value="#{TCCMB.getSubAreaList(TCCMB.area.grandeArea,TCCMB.area.area)}" 
                                       var="subarea" 
                                       itemLabel="#{subarea.titulo}" 
                                       itemValue="#{subarea}" />
                        <f:ajax render="areaesp" event="change" listener="#{TCCMB.getAreaEspList(TCCMB.area.grandeArea, TCCMB.area.area, TCCMB.area.subArea)}"/>
                    </h:selectOneMenu>
                    <h:message for="subarea" style="color:red" />

                    <h:outputLabel for="areaesp">
                        <h:outputText value="Area Específica"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="areaesp" value="#{TCCMB.area}" converter="generic" required="true" >
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItems value="#{TCCMB.getAreaEspList(TCCMB.area.grandeArea, TCCMB.area.area, TCCMB.area.subArea)}" 
                                       var="areaesp" 
                                       itemLabel="#{areaesp.titulo}" 
                                       itemValue="#{areaesp}" />
                    </h:selectOneMenu>
                    <h:message for="areaesp" style="color:red" />

                    <h:outputLabel for="avalexter">
                        <h:outputText value="Avaliador externo:"/>
                    </h:outputLabel>
                    <h:inputText id="avalexter" value="#{TCCMB.TCC.avaliadorExterno}"
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="avalexter" style="color:red" />

                    <h:outputLabel for="avalint">
                        <h:outputText value="Avaliador interno:"/>
                    </h:outputLabel>
                    <h:inputText id="avalint" value="#{TCCMB.TCC.avaliadorInterno}" 
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="avalint" style="color:red" />

                    <h:outputLabel for="dataDefesa">
                        <h:outputText value="Data da Defesa"/>
                    </h:outputLabel>
                    <h:inputText id="dataDefesa"
                                 value="#{TCCMB.TCC.dataDefesa}" >
                        <f:convertDateTime type="date" dateStyle="short" pattern="dd/MM/yyyy"/> 
                    </h:inputText>
                    <h:message for="dataDefesa" style="color:red" />

                    <h:outputLabel for="imprenta">
                        <h:outputText value="Imprenta:"/>
                    </h:outputLabel>
                    <h:inputText id="imprenta" value="#{TCCMB.TCC.imprenta}"
                                 validatorMessage="Valor inválido.">
                        <f:validateLength minimum="3" maximum="50"/>
                    </h:inputText>
                    <h:message for="imprenta" style="color:red" />

                    <h:outputLabel for="nota">
                        <h:outputText value="Nota:"/>
                    </h:outputLabel>
                    <h:inputText id="nota" value="#{TCCMB.TCC.nota}" 
                                 validatorMessage="Valor inválido.">
                        <f:validateDoubleRange minimum="00.00" maximum="10.00" />
                    </h:inputText>
                    <h:message for="nota" style="color:red" />

                    <h:outputLabel for="statusdesafa">
                        <h:outputText value="Status da defesa:"/>
                    </h:outputLabel>
                    <h:selectOneMenu id="statusdefesa" value="#{TCCMB.TCC.status}" >
                        <f:selectItem itemLabel="Selecione" itemValue=""/>
                        <f:selectItem itemLabel="APROVADA" itemValue="1"/>  
                        <f:selectItem itemLabel="REPROVADA" itemValue="2"/>
                        <f:selectItem itemLabel="ADIADA" itemValue="2"/>
                    </h:selectOneMenu>
                    <h:message for="statusdefesa" style="color:red" />

                    <h:commandButton id="register" styleClass="button" 
                                     action="#{TCCMB.salva()}"
                                     value="Adicionar"
                                     />
                </h:panelGrid>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>